epochs: 40
batch_size: 32
num_workers: 8

device: cuda
seed: 42

lr: 0.001
weight_decay: 0.0001

optimizer: adamw

project: runs/classifier
name: ${classifier_model.name}_${classifier_data.name}

save_best_only: true
resume: false

use_amp: true
pin_memory: true

early_stopping_patience: 10