from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Sequence


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Render the shape-similarity synthetic scene plan inside Blender or BlenderProc "
            "and write YOLO labels."
        )
    )
    parser.add_argument(
        "--scene-plan",
        type=Path,
        required=True,
        help="JSONL scene plan generated by scripts/plan_shape_similarity_synthetic.py.",
    )
    parser.add_argument(
        "--start-index",
        type=int,
        default=0,
        help="Optional start index into the scene plan for sharded rendering.",
    )
    parser.add_argument(
        "--count",
        type=int,
        default=None,
        help="Optional number of scenes to render after start-index.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing rendered images and labels.",
    )
    return parser.parse_args(argv)


def load_scene_rows(scene_plan_path: Path) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for line in scene_plan_path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        rows.append(json.loads(stripped))
    if not rows:
        raise ValueError(f"No scene rows found in {scene_plan_path}")
    return rows


def ensure_blender_runtime() -> tuple[object, object, object]:
    try:
        import bpy  # type: ignore
        import bpy_extras  # type: ignore
        from mathutils import Vector  # type: ignore
    except ImportError as exc:  # pragma: no cover - runtime-only guard
        raise SystemExit(
            "This script must run inside Blender or BlenderProc. "
            "Example: blenderproc run scripts/render_shape_similarity_blender.py -- --scene-plan data/shape_similarity_source/manifests/scene_plan.jsonl"
        ) from exc
    return bpy, bpy_extras, Vector


def reset_scene(bpy) -> None:
    bpy.ops.wm.read_factory_settings(use_empty=True)


def import_mesh(bpy, mesh_path: Path):
    suffix = mesh_path.suffix.lower()
    before_names = set(obj.name for obj in bpy.data.objects)
    if suffix == ".obj":
        bpy.ops.wm.obj_import(filepath=str(mesh_path))
    elif suffix == ".stl":
        bpy.ops.wm.stl_import(filepath=str(mesh_path))
    elif suffix in {".glb", ".gltf"}:
        bpy.ops.import_scene.gltf(filepath=str(mesh_path))
    elif suffix == ".fbx":
        bpy.ops.import_scene.fbx(filepath=str(mesh_path))
    elif suffix == ".ply":
        bpy.ops.wm.ply_import(filepath=str(mesh_path))
    else:
        raise ValueError(f"Unsupported mesh format for {mesh_path}")

    imported = [obj for obj in bpy.data.objects if obj.name not in before_names and obj.type == "MESH"]
    if not imported:
        raise RuntimeError(f"Mesh import created no MESH objects for {mesh_path}")
    active = imported[0]
    bpy.context.view_layer.objects.active = active
    for obj in imported:
        obj.select_set(True)
    bpy.ops.object.join()
    return bpy.context.view_layer.objects.active


def create_principled_material(bpy, *, name: str, base_color: tuple[float, float, float, float], metallic: float, roughness: float):
    material = bpy.data.materials.new(name=name)
    material.use_nodes = True
    principled = material.node_tree.nodes.get("Principled BSDF")
    if principled is None:
        raise RuntimeError("Could not find Principled BSDF node")
    principled.inputs["Base Color"].default_value = base_color
    principled.inputs["Metallic"].default_value = metallic
    principled.inputs["Roughness"].default_value = roughness
    return material


def color_rgba(color_name: str) -> tuple[float, float, float, float]:
    palette = {
        "matte_blue": (0.22, 0.34, 0.42, 1.0),
        "matte_gray": (0.52, 0.54, 0.56, 1.0),
        "brushed_steel": (0.68, 0.69, 0.70, 1.0),
        "dark_graphite": (0.21, 0.23, 0.24, 1.0),
    }
    return palette.get(color_name, (0.50, 0.50, 0.50, 1.0))


def create_tray_plane(bpy, tray_payload: dict[str, object]):
    tray_size = tray_payload["size_m"]
    bpy.ops.mesh.primitive_plane_add(size=1.0, location=(0.0, 0.0, 0.0))
    tray = bpy.context.active_object
    tray.name = "TrayPlane"
    tray.scale[0] = float(tray_size[0]) / 2.0
    tray.scale[1] = float(tray_size[1]) / 2.0
    material = create_principled_material(
        bpy,
        name="TrayMaterial",
        base_color=color_rgba(str(tray_payload["base_color"])),
        metallic=0.0,
        roughness=float(tray_payload["roughness"]),
    )
    tray.data.materials.append(material)
    return tray


def normalize_object_scale(mesh_object, Vector, scale_hint_meters: float) -> None:
    local_bbox = [Vector(corner) for corner in mesh_object.bound_box]
    bbox_world = [mesh_object.matrix_world @ corner for corner in local_bbox]
    xs = [point.x for point in bbox_world]
    ys = [point.y for point in bbox_world]
    zs = [point.z for point in bbox_world]
    current_max_dim = max(max(xs) - min(xs), max(ys) - min(ys), max(zs) - min(zs))
    if current_max_dim <= 0:
        return
    scale_factor = scale_hint_meters / current_max_dim
    mesh_object.scale = tuple(component * scale_factor for component in mesh_object.scale)


def place_object(mesh_object, target_payload: dict[str, object]) -> None:
    location = target_payload["location_xyz"]
    rotation_deg = target_payload["rotation_euler_deg"]
    mesh_object.location = tuple(float(value) for value in location)
    mesh_object.rotation_euler = tuple(math.radians(float(value)) for value in rotation_deg)


def assign_object_material(bpy, mesh_object, target_payload: dict[str, object]) -> None:
    material = create_principled_material(
        bpy,
        name="ToolMaterial",
        base_color=(0.77, 0.78, 0.79, 1.0),
        metallic=float(target_payload["material_metallic"]),
        roughness=float(target_payload["material_roughness"]),
    )
    mesh_object.data.materials.clear()
    mesh_object.data.materials.append(material)


def add_camera(bpy, camera_payload: dict[str, object]):
    bpy.ops.object.camera_add(location=(0.0, 0.0, float(camera_payload["distance_m"])))
    camera = bpy.context.active_object
    camera.name = "TrayCamera"
    camera.rotation_euler = (0.0, 0.0, 0.0)
    return camera


def add_light(bpy, light_payload: dict[str, object]):
    bpy.ops.object.light_add(
        type="AREA",
        location=(
            float(light_payload["x_m"]),
            float(light_payload["y_m"]),
            float(light_payload["z_m"]),
        ),
    )
    light = bpy.context.active_object
    light.data.energy = float(light_payload["energy"])
    light.scale = (0.35, 0.35, 0.35)
    return light


def configure_render(bpy, camera, resolution_payload: dict[str, object], image_path: Path) -> None:
    bpy.context.scene.camera = camera
    bpy.context.scene.render.engine = "CYCLES"
    bpy.context.scene.cycles.samples = 32
    bpy.context.scene.render.resolution_x = int(resolution_payload["width"])
    bpy.context.scene.render.resolution_y = int(resolution_payload["height"])
    bpy.context.scene.render.image_settings.file_format = "PNG"
    bpy.context.scene.render.filepath = str(image_path)


def projected_bbox_yolo(bpy_extras, scene, camera, mesh_object) -> tuple[float, float, float, float] | None:
    vertices = []
    for vertex in mesh_object.data.vertices:
        world_coord = mesh_object.matrix_world @ vertex.co
        projected = bpy_extras.object_utils.world_to_camera_view(scene, camera, world_coord)
        vertices.append(projected)
    visible = [vertex for vertex in vertices if 0.0 <= vertex.z <= 1.0]
    if not visible:
        return None
    min_x = min(vertex.x for vertex in visible)
    max_x = max(vertex.x for vertex in visible)
    min_y = min(vertex.y for vertex in visible)
    max_y = max(vertex.y for vertex in visible)
    min_x = max(0.0, min(1.0, min_x))
    max_x = max(0.0, min(1.0, max_x))
    min_y = max(0.0, min(1.0, min_y))
    max_y = max(0.0, min(1.0, max_y))
    if max_x <= min_x or max_y <= min_y:
        return None
    center_x = (min_x + max_x) / 2.0
    center_y = 1.0 - ((min_y + max_y) / 2.0)
    width = max_x - min_x
    height = max_y - min_y
    return center_x, center_y, width, height


def write_label(label_path: Path, class_id: int, bbox: tuple[float, float, float, float]) -> None:
    label_path.parent.mkdir(parents=True, exist_ok=True)
    cx, cy, width, height = bbox
    label_path.write_text(
        f"{class_id} {cx:.6f} {cy:.6f} {width:.6f} {height:.6f}\n",
        encoding="utf-8",
    )


def write_metadata(metadata_path: Path, payload: dict[str, object]) -> None:
    metadata_path.parent.mkdir(parents=True, exist_ok=True)
    metadata_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def render_scene(bpy, bpy_extras, Vector, scene_row: dict[str, object], overwrite: bool) -> None:
    image_path = Path(str(scene_row["image_path"]))
    label_path = Path(str(scene_row["label_path"]))
    metadata_path = Path(str(scene_row["metadata_path"]))
    if image_path.exists() and not overwrite:
        return

    reset_scene(bpy)
    create_tray_plane(bpy, dict(scene_row["tray"]))
    mesh_object = import_mesh(bpy, Path(str(scene_row["mesh_path"])))
    normalize_object_scale(mesh_object, Vector, float(scene_row["target_object"]["scale_hint_meters"]))
    place_object(mesh_object, dict(scene_row["target_object"]))
    assign_object_material(bpy, mesh_object, dict(scene_row["target_object"]))
    camera = add_camera(bpy, dict(scene_row["camera"]))
    add_light(bpy, dict(scene_row["lighting"]))
    configure_render(bpy, camera, dict(scene_row["resolution"]), image_path)
    bpy.ops.render.render(write_still=True)

    bbox = projected_bbox_yolo(bpy_extras, bpy.context.scene, camera, mesh_object)
    if bbox is None:
        raise RuntimeError(f"Rendered scene {scene_row['sample_id']} but could not compute a visible bounding box.")
    write_label(label_path, int(scene_row["class_id"]), bbox)
    write_metadata(
        metadata_path,
        {
            "sample_id": scene_row["sample_id"],
            "scene_id": scene_row["scene_id"],
            "class_name": scene_row["class_name"],
            "class_id": scene_row["class_id"],
            "mesh_id": scene_row["mesh_id"],
            "mesh_split": scene_row["mesh_split"],
            "condition_id": scene_row["condition_id"],
            "image_path": str(image_path),
            "label_path": str(label_path),
            "bbox_yolo": {
                "cx": bbox[0],
                "cy": bbox[1],
                "width": bbox[2],
                "height": bbox[3],
            },
        },
    )


def main(argv: Sequence[str] | None = None) -> None:
    bpy, bpy_extras, Vector = ensure_blender_runtime()
    args = parse_args(argv)
    scene_rows = load_scene_rows(args.scene_plan)

    start = max(0, args.start_index)
    end = len(scene_rows) if args.count is None else min(len(scene_rows), start + args.count)
    selected = scene_rows[start:end]
    if not selected:
        raise SystemExit("No scenes selected for rendering.")

    print(f"Rendering {len(selected)} scene(s) from {args.scene_plan}")
    for index, scene_row in enumerate(selected, start=1):
        render_scene(bpy, bpy_extras, Vector, scene_row, overwrite=args.overwrite)
        print(f"[{index}/{len(selected)}] {scene_row['sample_id']}")


if __name__ == "__main__":
    import sys

    forwarded_args = sys.argv[1:]
    if "--" in forwarded_args:
        forwarded_args = forwarded_args[forwarded_args.index("--") + 1 :]
    main(forwarded_args)
